// 本文件由 scripts/generate_error_codes.ts 自动生成，请勿手动修改。
// 源数据: shared/error_codes.json


export type ErrorCategory = 'type' | 'effect' | 'capability' | 'scope' | 'pii' | 'async';
export type ErrorSeverity = 'error' | 'warning' | 'info';

export const enum ErrorCode {
  TYPE_MISMATCH = "E001",
  TYPE_MISMATCH_ASSIGN = "E002",
  RETURN_TYPE_MISMATCH = "E003",
  TYPE_VAR_UNDECLARED = "E004",
  TYPE_PARAM_UNUSED = "E005",
  TYPEVAR_LIKE_UNDECLARED = "E006",
  TYPEVAR_INCONSISTENT = "E007",
  IF_BRANCH_MISMATCH = "E008",
  MATCH_BRANCH_MISMATCH = "E009",
  INTEGER_PATTERN_TYPE = "E010",
  UNKNOWN_FIELD = "E011",
  FIELD_TYPE_MISMATCH = "E012",
  MISSING_REQUIRED_FIELD = "E013",
  NOT_CALL_ARITY = "E014",
  AWAIT_TYPE = "E015",
  DUPLICATE_ENUM_CASE = "E016",
  NON_EXHAUSTIVE_MAYBE = "E017",
  NON_EXHAUSTIVE_ENUM = "E018",
  AMBIGUOUS_INTEROP_NUMERIC = "E019",
  LIST_ELEMENT_TYPE_MISMATCH = "E020",
  OPTIONAL_EXPECTED = "E021",
  WORKFLOW_COMPENSATE_TYPE = "E022",
  WORKFLOW_COMPENSATE_MISSING = "E023",
  WORKFLOW_RETRY_INVALID = "E024",
  WORKFLOW_TIMEOUT_INVALID = "E025",
  WORKFLOW_MISSING_IO_EFFECT = "E026",
  WORKFLOW_UNDECLARED_CAPABILITY = "E027",
  COMPENSATE_NEW_CAPABILITY = "E028",
  WORKFLOW_UNKNOWN_STEP_DEPENDENCY = "E029",
  WORKFLOW_CIRCULAR_DEPENDENCY = "E030",
  PII_ASSIGN_DOWNGRADE = "E070",
  PII_SINK_UNSANITIZED = "E072",
  PII_ARG_VIOLATION = "E073",
  DUPLICATE_IMPORT_ALIAS = "E100",
  UNDEFINED_VARIABLE = "E101",
  DUPLICATE_SYMBOL = "E102",
  EFF_MISSING_IO = "E200",
  EFF_MISSING_CPU = "E201",
  EFF_SUPERFLUOUS_IO_CPU_ONLY = "E202",
  EFF_SUPERFLUOUS_IO = "E203",
  EFF_SUPERFLUOUS_CPU = "E204",
  EFF_INFER_MISSING_IO = "E205",
  EFF_INFER_MISSING_CPU = "E206",
  EFF_INFER_REDUNDANT_IO = "E207",
  EFF_INFER_REDUNDANT_CPU = "E208",
  EFF_INFER_REDUNDANT_CPU_WITH_IO = "E209",
  EFFECT_VAR_UNDECLARED = "E210",
  EFFECT_VAR_UNRESOLVED = "E211",
  CAPABILITY_NOT_ALLOWED = "E300",
  EFF_CAP_MISSING = "E301",
  EFF_CAP_SUPERFLUOUS = "E302",
  CAPABILITY_INFER_MISSING_IO = "E303",
  CAPABILITY_INFER_MISSING_CPU = "E304",
  PII_HTTP_UNENCRYPTED = "E400",
  PII_ANNOTATION_MISSING = "E401",
  PII_SENSITIVITY_MISMATCH = "E402",
  PII_MISSING_CONSENT_CHECK = "E403",
  ASYNC_START_NOT_WAITED = "E500",
  ASYNC_WAIT_NOT_STARTED = "E501",
  ASYNC_DUPLICATE_START = "E502",
  ASYNC_DUPLICATE_WAIT = "E503",
  ASYNC_WAIT_BEFORE_START = "E504",
  PII_IMPLICIT_UPLEVEL = "W071",
  PII_SINK_UNKNOWN = "W074",
  WORKFLOW_RETRY_INCONSISTENT = "W105",
  WORKFLOW_TIMEOUT_UNREASONABLE = "W106",
}

export interface ErrorMetadata {
  readonly code: ErrorCode;
  readonly category: ErrorCategory;
  readonly severity: ErrorSeverity;
  readonly message: string;
  readonly help: string;
}

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  [ErrorCode.TYPE_MISMATCH]: "Type mismatch: expected {expected}, got {actual}",
  [ErrorCode.TYPE_MISMATCH_ASSIGN]: "Type mismatch assigning to '{name}': {expected} vs {actual}",
  [ErrorCode.RETURN_TYPE_MISMATCH]: "Return type mismatch: expected {expected}, got {actual}",
  [ErrorCode.TYPE_VAR_UNDECLARED]: "Type variable '{name}' is used in '{func}' but not declared in its type parameters.",
  [ErrorCode.TYPE_PARAM_UNUSED]: "Type parameter '{name}' on '{func}' is declared but not used.",
  [ErrorCode.TYPEVAR_LIKE_UNDECLARED]: "Type variable-like '{name}' is used in '{func}' but not declared; declare it with 'of {name}'.",
  [ErrorCode.TYPEVAR_INCONSISTENT]: "Type variable '{name}' inferred inconsistently: {previous} vs {actual}",
  [ErrorCode.IF_BRANCH_MISMATCH]: "If branch type mismatch: then {thenType} vs else {elseType}",
  [ErrorCode.MATCH_BRANCH_MISMATCH]: "Match case return types differ: {expected} vs {actual}",
  [ErrorCode.INTEGER_PATTERN_TYPE]: "Integer pattern used on non-Int scrutinee ({scrutineeType})",
  [ErrorCode.UNKNOWN_FIELD]: "Unknown field '{field}' for {type}",
  [ErrorCode.FIELD_TYPE_MISMATCH]: "Field '{field}' expects {expected}, got {actual}",
  [ErrorCode.MISSING_REQUIRED_FIELD]: "Construction of {type} missing required field '{field}'",
  [ErrorCode.NOT_CALL_ARITY]: "not(...) expects 1 argument",
  [ErrorCode.AWAIT_TYPE]: "await expects Maybe<T> or Result<T,E>, got {type}",
  [ErrorCode.DUPLICATE_ENUM_CASE]: "Duplicate enum case '{case}' in match on {type}.",
  [ErrorCode.NON_EXHAUSTIVE_MAYBE]: "Non-exhaustive match on Maybe type; missing {missing} case.",
  [ErrorCode.NON_EXHAUSTIVE_ENUM]: "Non-exhaustive match on {type}; missing: {missing}",
  [ErrorCode.AMBIGUOUS_INTEROP_NUMERIC]: "Ambiguous interop call '{target}': mixing numeric kinds (Int={hasInt}, Long={hasLong}, Double={hasDouble}). Overload resolution may widen/box implicitly.",
  [ErrorCode.LIST_ELEMENT_TYPE_MISMATCH]: "List literal element type mismatch: expected {expected}, got {actual}",
  [ErrorCode.OPTIONAL_EXPECTED]: "Optional value required here: expected Maybe or Option, but got {actual}",
  [ErrorCode.WORKFLOW_COMPENSATE_TYPE]: "Compensate block for step '{step}' must return Result<Unit, {expectedErr}>, got {actual}",
  [ErrorCode.WORKFLOW_COMPENSATE_MISSING]: "Step '{step}' performs side effects but does not define a compensate block.",
  [ErrorCode.WORKFLOW_RETRY_INVALID]: "Workflow retry max attempts must be greater than zero (actual: {maxAttempts}).",
  [ErrorCode.WORKFLOW_TIMEOUT_INVALID]: "Workflow timeout must be greater than zero milliseconds (actual: {milliseconds}).",
  [ErrorCode.WORKFLOW_MISSING_IO_EFFECT]: "Workflow '{func}' must declare @io effect before using a 'workflow' block.",
  [ErrorCode.WORKFLOW_UNDECLARED_CAPABILITY]: "Workflow '{func}' step '{step}' uses capability {capability} that is not declared on the function header.",
  [ErrorCode.COMPENSATE_NEW_CAPABILITY]: "Compensate block for step '{step}' in function '{func}' introduces new capability {capability} that does not appear in the main step body.",
  [ErrorCode.WORKFLOW_UNKNOWN_STEP_DEPENDENCY]: "Workflow step '{step}' depends on undefined step '{dependency}'.",
  [ErrorCode.WORKFLOW_CIRCULAR_DEPENDENCY]: "Workflow contains circular step dependency: {cycle}",
  [ErrorCode.PII_ASSIGN_DOWNGRADE]: "Cannot assign PII data to lower-level target: {source} -> {target}",
  [ErrorCode.PII_SINK_UNSANITIZED]: "PII level {level} data output to {sinkKind} without sanitization",
  [ErrorCode.PII_ARG_VIOLATION]: "PII argument type mismatch: expected {expected}, got {actual}",
  [ErrorCode.DUPLICATE_IMPORT_ALIAS]: "Duplicate import alias '{alias}'.",
  [ErrorCode.UNDEFINED_VARIABLE]: "Undefined variable: {name}",
  [ErrorCode.DUPLICATE_SYMBOL]: "Symbol '{name}' is already defined in this scope.",
  [ErrorCode.EFF_MISSING_IO]: "Function '{func}' may perform I/O but is missing @io effect.",
  [ErrorCode.EFF_MISSING_CPU]: "Function '{func}' may perform CPU-bound work but is missing @cpu (or @io) effect.",
  [ErrorCode.EFF_SUPERFLUOUS_IO_CPU_ONLY]: "Function '{func}' declares @io but only CPU-like work found; @io subsumes @cpu and may be unnecessary.",
  [ErrorCode.EFF_SUPERFLUOUS_IO]: "Function '{func}' declares @io but no obvious I/O found.",
  [ErrorCode.EFF_SUPERFLUOUS_CPU]: "Function '{func}' declares @cpu but no obvious CPU-bound work found.",
  [ErrorCode.EFF_INFER_MISSING_IO]: "Function '{func}' missing @io effect declaration, inference requires IO.",
  [ErrorCode.EFF_INFER_MISSING_CPU]: "Function '{func}' missing @cpu effect declaration, inference requires CPU (or @io).",
  [ErrorCode.EFF_INFER_REDUNDANT_IO]: "Function '{func}' declares @io but no IO side effects inferred.",
  [ErrorCode.EFF_INFER_REDUNDANT_CPU]: "Function '{func}' declares @cpu but no CPU side effects inferred.",
  [ErrorCode.EFF_INFER_REDUNDANT_CPU_WITH_IO]: "Function '{func}' declares both @cpu and @io; @cpu is redundant since @io is required.",
  [ErrorCode.EFFECT_VAR_UNDECLARED]: "Effect variable {var} undeclared",
  [ErrorCode.EFFECT_VAR_UNRESOLVED]: "Effect variable {vars} could not be resolved to concrete effects",
  [ErrorCode.CAPABILITY_NOT_ALLOWED]: "Function '{func}' requires {cap} capability but manifest for module '{module}' denies it.",
  [ErrorCode.EFF_CAP_MISSING]: "Function '{func}' uses {cap} capability but header declares [{declared}].",
  [ErrorCode.EFF_CAP_SUPERFLUOUS]: "Function '{func}' declares {cap} capability but it is not used.",
  [ErrorCode.CAPABILITY_INFER_MISSING_IO]: "Function '{func}' uses IO capabilities [{capabilities}] but is missing @io effect (e.g., {calls}).",
  [ErrorCode.CAPABILITY_INFER_MISSING_CPU]: "Function '{func}' performs CPU capability calls (e.g., {calls}) but declares neither @cpu nor @io effect.",
  [ErrorCode.PII_HTTP_UNENCRYPTED]: "PII data transmitted over HTTP without encryption",
  [ErrorCode.PII_ANNOTATION_MISSING]: "PII annotation missing for value flowing into '{sink}'",
  [ErrorCode.PII_SENSITIVITY_MISMATCH]: "PII sensitivity mismatch: required {required}, got {actual}",
  [ErrorCode.PII_MISSING_CONSENT_CHECK]: "Function '{func}' processes PII data without consent check (GDPR Art. 6)",
  [ErrorCode.ASYNC_START_NOT_WAITED]: "Started async task '{task}' not waited",
  [ErrorCode.ASYNC_WAIT_NOT_STARTED]: "Waiting for async task '{task}' that was never started",
  [ErrorCode.ASYNC_DUPLICATE_START]: "Async task '{task}' started multiple times ({count} occurrences)",
  [ErrorCode.ASYNC_DUPLICATE_WAIT]: "Async task '{task}' waited multiple times ({count} occurrences)",
  [ErrorCode.ASYNC_WAIT_BEFORE_START]: "Wait for async task '{task}' occurs before any matching start",
  [ErrorCode.PII_IMPLICIT_UPLEVEL]: "Implicit PII level escalation detected: {source} -> {target}",
  [ErrorCode.PII_SINK_UNKNOWN]: "PII data may flow to {sinkKind} without annotation",
  [ErrorCode.WORKFLOW_RETRY_INCONSISTENT]: "Workflow retry configuration may be unreasonable: {reason}",
  [ErrorCode.WORKFLOW_TIMEOUT_UNREASONABLE]: "Workflow timeout configuration may be unreasonable: {reason}",
};

export const ERROR_METADATA: Record<ErrorCode, ErrorMetadata> = {
  [ErrorCode.TYPE_MISMATCH]: { code: ErrorCode.TYPE_MISMATCH, category: 'type', severity: 'error', message: "Type mismatch: expected {expected}, got {actual}", help: "Check that the type annotation matches the inferred expression type." },
  [ErrorCode.TYPE_MISMATCH_ASSIGN]: { code: ErrorCode.TYPE_MISMATCH_ASSIGN, category: 'type', severity: 'error', message: "Type mismatch assigning to '{name}': {expected} vs {actual}", help: "Ensure the variable's previous binding type matches the current assignment." },
  [ErrorCode.RETURN_TYPE_MISMATCH]: { code: ErrorCode.RETURN_TYPE_MISMATCH, category: 'type', severity: 'error', message: "Return type mismatch: expected {expected}, got {actual}", help: "Check that the return statement matches the declared return type." },
  [ErrorCode.TYPE_VAR_UNDECLARED]: { code: ErrorCode.TYPE_VAR_UNDECLARED, category: 'type', severity: 'error', message: "Type variable '{name}' is used in '{func}' but not declared in its type parameters.", help: "Declare used type variables in the function signature's 'of' clause." },
  [ErrorCode.TYPE_PARAM_UNUSED]: { code: ErrorCode.TYPE_PARAM_UNUSED, category: 'type', severity: 'warning', message: "Type parameter '{name}' on '{func}' is declared but not used.", help: "Remove unused type parameters to avoid confusion." },
  [ErrorCode.TYPEVAR_LIKE_UNDECLARED]: { code: ErrorCode.TYPEVAR_LIKE_UNDECLARED, category: 'type', severity: 'error', message: "Type variable-like '{name}' is used in '{func}' but not declared; declare it with 'of {name}'.", help: "For names that look like type variables, declare them in the 'of' clause." },
  [ErrorCode.TYPEVAR_INCONSISTENT]: { code: ErrorCode.TYPEVAR_INCONSISTENT, category: 'type', severity: 'error', message: "Type variable '{name}' inferred inconsistently: {previous} vs {actual}", help: "Ensure all usage sites of a type variable produce the same concrete type." },
  [ErrorCode.IF_BRANCH_MISMATCH]: { code: ErrorCode.IF_BRANCH_MISMATCH, category: 'type', severity: 'error', message: "If branch type mismatch: then {thenType} vs else {elseType}", help: "Ensure both branches of an if expression return the same type." },
  [ErrorCode.MATCH_BRANCH_MISMATCH]: { code: ErrorCode.MATCH_BRANCH_MISMATCH, category: 'type', severity: 'error', message: "Match case return types differ: {expected} vs {actual}", help: "Check that all match branches return the same type." },
  [ErrorCode.INTEGER_PATTERN_TYPE]: { code: ErrorCode.INTEGER_PATTERN_TYPE, category: 'type', severity: 'error', message: "Integer pattern used on non-Int scrutinee ({scrutineeType})", help: "Only use integer patterns on Int-typed match expressions." },
  [ErrorCode.UNKNOWN_FIELD]: { code: ErrorCode.UNKNOWN_FIELD, category: 'type', severity: 'error', message: "Unknown field '{field}' for {type}", help: "Check that the field name is correct for the data type." },
  [ErrorCode.FIELD_TYPE_MISMATCH]: { code: ErrorCode.FIELD_TYPE_MISMATCH, category: 'type', severity: 'error', message: "Field '{field}' expects {expected}, got {actual}", help: "Verify the field initializer expression matches the declared type." },
  [ErrorCode.MISSING_REQUIRED_FIELD]: { code: ErrorCode.MISSING_REQUIRED_FIELD, category: 'type', severity: 'error', message: "Construction of {type} missing required field '{field}'", help: "Provide all required fields declared in the data type." },
  [ErrorCode.NOT_CALL_ARITY]: { code: ErrorCode.NOT_CALL_ARITY, category: 'type', severity: 'error', message: "not(...) expects 1 argument", help: "Adjust the not() call to have exactly 1 argument." },
  [ErrorCode.AWAIT_TYPE]: { code: ErrorCode.AWAIT_TYPE, category: 'type', severity: 'warning', message: "await expects Maybe<T> or Result<T,E>, got {type}", help: "Only use await on Maybe or Result types." },
  [ErrorCode.DUPLICATE_ENUM_CASE]: { code: ErrorCode.DUPLICATE_ENUM_CASE, category: 'type', severity: 'warning', message: "Duplicate enum case '{case}' in match on {type}.", help: "Remove duplicate enum branches to keep the match concise." },
  [ErrorCode.NON_EXHAUSTIVE_MAYBE]: { code: ErrorCode.NON_EXHAUSTIVE_MAYBE, category: 'type', severity: 'warning', message: "Non-exhaustive match on Maybe type; missing {missing} case.", help: "Add both null and non-null branches for Maybe matches." },
  [ErrorCode.NON_EXHAUSTIVE_ENUM]: { code: ErrorCode.NON_EXHAUSTIVE_ENUM, category: 'type', severity: 'warning', message: "Non-exhaustive match on {type}; missing: {missing}", help: "Add all uncovered enum branches, or add a wildcard." },
  [ErrorCode.AMBIGUOUS_INTEROP_NUMERIC]: { code: ErrorCode.AMBIGUOUS_INTEROP_NUMERIC, category: 'type', severity: 'warning', message: "Ambiguous interop call '{target}': mixing numeric kinds (Int={hasInt}, Long={hasLong}, Double={hasDouble}). Overload resolution may widen/box implicitly.", help: "Unify numeric argument types in interop calls to avoid implicit boxing and widening." },
  [ErrorCode.LIST_ELEMENT_TYPE_MISMATCH]: { code: ErrorCode.LIST_ELEMENT_TYPE_MISMATCH, category: 'type', severity: 'error', message: "List literal element type mismatch: expected {expected}, got {actual}", help: "Ensure all elements in a list literal have the same type." },
  [ErrorCode.OPTIONAL_EXPECTED]: { code: ErrorCode.OPTIONAL_EXPECTED, category: 'type', severity: 'error', message: "Optional value required here: expected Maybe or Option, but got {actual}", help: "Pass a Maybe/Option type or explicitly wrap the value." },
  [ErrorCode.WORKFLOW_COMPENSATE_TYPE]: { code: ErrorCode.WORKFLOW_COMPENSATE_TYPE, category: 'type', severity: 'error', message: "Compensate block for step '{step}' must return Result<Unit, {expectedErr}>, got {actual}", help: "Ensure the compensate block returns Result<Unit, E> where E is the step error type." },
  [ErrorCode.WORKFLOW_COMPENSATE_MISSING]: { code: ErrorCode.WORKFLOW_COMPENSATE_MISSING, category: 'effect', severity: 'warning', message: "Step '{step}' performs side effects but does not define a compensate block.", help: "Provide a compensate block for steps with IO side effects to enable rollback." },
  [ErrorCode.WORKFLOW_RETRY_INVALID]: { code: ErrorCode.WORKFLOW_RETRY_INVALID, category: 'type', severity: 'error', message: "Workflow retry max attempts must be greater than zero (actual: {maxAttempts}).", help: "Set retry.maxAttempts to a positive integer." },
  [ErrorCode.WORKFLOW_TIMEOUT_INVALID]: { code: ErrorCode.WORKFLOW_TIMEOUT_INVALID, category: 'type', severity: 'error', message: "Workflow timeout must be greater than zero milliseconds (actual: {milliseconds}).", help: "Set the timeout to a positive value to ensure compensate logic can be triggered." },
  [ErrorCode.WORKFLOW_MISSING_IO_EFFECT]: { code: ErrorCode.WORKFLOW_MISSING_IO_EFFECT, category: 'effect', severity: 'error', message: "Workflow '{func}' must declare @io effect before using a 'workflow' block.", help: "Add @io effect declaration to the function header." },
  [ErrorCode.WORKFLOW_UNDECLARED_CAPABILITY]: { code: ErrorCode.WORKFLOW_UNDECLARED_CAPABILITY, category: 'capability', severity: 'error', message: "Workflow '{func}' step '{step}' uses capability {capability} that is not declared on the function header.", help: "Declare {capability} in the function header or adjust the step code." },
  [ErrorCode.COMPENSATE_NEW_CAPABILITY]: { code: ErrorCode.COMPENSATE_NEW_CAPABILITY, category: 'capability', severity: 'error', message: "Compensate block for step '{step}' in function '{func}' introduces new capability {capability} that does not appear in the main step body.", help: "Compensate blocks can only reuse capabilities from the main step body." },
  [ErrorCode.WORKFLOW_UNKNOWN_STEP_DEPENDENCY]: { code: ErrorCode.WORKFLOW_UNKNOWN_STEP_DEPENDENCY, category: 'scope', severity: 'error', message: "Workflow step '{step}' depends on undefined step '{dependency}'.", help: "Only reference declared step names in the current workflow." },
  [ErrorCode.WORKFLOW_CIRCULAR_DEPENDENCY]: { code: ErrorCode.WORKFLOW_CIRCULAR_DEPENDENCY, category: 'type', severity: 'error', message: "Workflow contains circular step dependency: {cycle}", help: "Remove or restructure circular dependencies to enable topological execution." },
  [ErrorCode.PII_ASSIGN_DOWNGRADE]: { code: ErrorCode.PII_ASSIGN_DOWNGRADE, category: 'type', severity: 'error', message: "Cannot assign PII data to lower-level target: {source} -> {target}", help: "Use a sanitization function or declare a matching @pii level on the target." },
  [ErrorCode.PII_SINK_UNSANITIZED]: { code: ErrorCode.PII_SINK_UNSANITIZED, category: 'type', severity: 'error', message: "PII level {level} data output to {sinkKind} without sanitization", help: "Call redact() or tokenize() before output to reduce sensitivity." },
  [ErrorCode.PII_ARG_VIOLATION]: { code: ErrorCode.PII_ARG_VIOLATION, category: 'type', severity: 'error', message: "PII argument type mismatch: expected {expected}, got {actual}", help: "Check the function signature to ensure PII levels and categories match." },
  [ErrorCode.DUPLICATE_IMPORT_ALIAS]: { code: ErrorCode.DUPLICATE_IMPORT_ALIAS, category: 'scope', severity: 'warning', message: "Duplicate import alias '{alias}'.", help: "Use unique aliases for different imports to avoid shadowing." },
  [ErrorCode.UNDEFINED_VARIABLE]: { code: ErrorCode.UNDEFINED_VARIABLE, category: 'scope', severity: 'error', message: "Undefined variable: {name}", help: "Declare and initialize the variable before use." },
  [ErrorCode.DUPLICATE_SYMBOL]: { code: ErrorCode.DUPLICATE_SYMBOL, category: 'scope', severity: 'error', message: "Symbol '{name}' is already defined in this scope.", help: "Choose a different name or check for unintended duplicate declarations." },
  [ErrorCode.EFF_MISSING_IO]: { code: ErrorCode.EFF_MISSING_IO, category: 'effect', severity: 'error', message: "Function '{func}' may perform I/O but is missing @io effect.", help: "Declare @io effect for functions that perform I/O." },
  [ErrorCode.EFF_MISSING_CPU]: { code: ErrorCode.EFF_MISSING_CPU, category: 'effect', severity: 'error', message: "Function '{func}' may perform CPU-bound work but is missing @cpu (or @io) effect.", help: "Declare @cpu or @io effect for CPU-intensive functions." },
  [ErrorCode.EFF_SUPERFLUOUS_IO_CPU_ONLY]: { code: ErrorCode.EFF_SUPERFLUOUS_IO_CPU_ONLY, category: 'effect', severity: 'info', message: "Function '{func}' declares @io but only CPU-like work found; @io subsumes @cpu and may be unnecessary.", help: "If the function only does CPU work, consider removing the redundant @io declaration." },
  [ErrorCode.EFF_SUPERFLUOUS_IO]: { code: ErrorCode.EFF_SUPERFLUOUS_IO, category: 'effect', severity: 'warning', message: "Function '{func}' declares @io but no obvious I/O found.", help: "Confirm @io is needed; remove if no I/O behavior exists." },
  [ErrorCode.EFF_SUPERFLUOUS_CPU]: { code: ErrorCode.EFF_SUPERFLUOUS_CPU, category: 'effect', severity: 'warning', message: "Function '{func}' declares @cpu but no obvious CPU-bound work found.", help: "Remove the redundant @cpu declaration or add corresponding CPU work." },
  [ErrorCode.EFF_INFER_MISSING_IO]: { code: ErrorCode.EFF_INFER_MISSING_IO, category: 'effect', severity: 'error', message: "Function '{func}' missing @io effect declaration, inference requires IO.", help: "Add @io effect based on inference results." },
  [ErrorCode.EFF_INFER_MISSING_CPU]: { code: ErrorCode.EFF_INFER_MISSING_CPU, category: 'effect', severity: 'error', message: "Function '{func}' missing @cpu effect declaration, inference requires CPU (or @io).", help: "Add @cpu or @io effect based on inference results." },
  [ErrorCode.EFF_INFER_REDUNDANT_IO]: { code: ErrorCode.EFF_INFER_REDUNDANT_IO, category: 'effect', severity: 'warning', message: "Function '{func}' declares @io but no IO side effects inferred.", help: "Confirm whether to keep the @io declaration." },
  [ErrorCode.EFF_INFER_REDUNDANT_CPU]: { code: ErrorCode.EFF_INFER_REDUNDANT_CPU, category: 'effect', severity: 'warning', message: "Function '{func}' declares @cpu but no CPU side effects inferred.", help: "Remove the @cpu declaration if no CPU side effects exist." },
  [ErrorCode.EFF_INFER_REDUNDANT_CPU_WITH_IO]: { code: ErrorCode.EFF_INFER_REDUNDANT_CPU_WITH_IO, category: 'effect', severity: 'warning', message: "Function '{func}' declares both @cpu and @io; @cpu is redundant since @io is required.", help: "Keep @io only; remove the redundant @cpu." },
  [ErrorCode.EFFECT_VAR_UNDECLARED]: { code: ErrorCode.EFFECT_VAR_UNDECLARED, category: 'type', severity: 'error', message: "Effect variable {var} undeclared", help: "Add the effect type parameter to the function signature's effect parameter list." },
  [ErrorCode.EFFECT_VAR_UNRESOLVED]: { code: ErrorCode.EFFECT_VAR_UNRESOLVED, category: 'type', severity: 'error', message: "Effect variable {vars} could not be resolved to concrete effects", help: "Provide explicit effects (pure/cpu/io/workflow) or remove unused effect variables." },
  [ErrorCode.CAPABILITY_NOT_ALLOWED]: { code: ErrorCode.CAPABILITY_NOT_ALLOWED, category: 'capability', severity: 'error', message: "Function '{func}' requires {cap} capability but manifest for module '{module}' denies it.", help: "Update the capability manifest or modify the function to comply." },
  [ErrorCode.EFF_CAP_MISSING]: { code: ErrorCode.EFF_CAP_MISSING, category: 'capability', severity: 'error', message: "Function '{func}' uses {cap} capability but header declares [{declared}].", help: "Declare the actually used capabilities in the function header." },
  [ErrorCode.EFF_CAP_SUPERFLUOUS]: { code: ErrorCode.EFF_CAP_SUPERFLUOUS, category: 'capability', severity: 'info', message: "Function '{func}' declares {cap} capability but it is not used.", help: "Remove unused capability declarations for clarity." },
  [ErrorCode.CAPABILITY_INFER_MISSING_IO]: { code: ErrorCode.CAPABILITY_INFER_MISSING_IO, category: 'capability', severity: 'error', message: "Function '{func}' uses IO capabilities [{capabilities}] but is missing @io effect (e.g., {calls}).", help: "Declare @io effect in the function header, or remove related calls to stay pure." },
  [ErrorCode.CAPABILITY_INFER_MISSING_CPU]: { code: ErrorCode.CAPABILITY_INFER_MISSING_CPU, category: 'capability', severity: 'error', message: "Function '{func}' performs CPU capability calls (e.g., {calls}) but declares neither @cpu nor @io effect.", help: "Add @cpu or @io effect to cover CPU capabilities." },
  [ErrorCode.PII_HTTP_UNENCRYPTED]: { code: ErrorCode.PII_HTTP_UNENCRYPTED, category: 'pii', severity: 'error', message: "PII data transmitted over HTTP without encryption", help: "Use an encrypted channel (HTTPS) or sanitize before transmitting PII data." },
  [ErrorCode.PII_ANNOTATION_MISSING]: { code: ErrorCode.PII_ANNOTATION_MISSING, category: 'pii', severity: 'error', message: "PII annotation missing for value flowing into '{sink}'", help: "Add @pii annotation to sensitive data for tracking." },
  [ErrorCode.PII_SENSITIVITY_MISMATCH]: { code: ErrorCode.PII_SENSITIVITY_MISMATCH, category: 'pii', severity: 'warning', message: "PII sensitivity mismatch: required {required}, got {actual}", help: "Adjust the data sensitivity level or update the process requirements." },
  [ErrorCode.PII_MISSING_CONSENT_CHECK]: { code: ErrorCode.PII_MISSING_CONSENT_CHECK, category: 'pii', severity: 'warning', message: "Function '{func}' processes PII data without consent check (GDPR Art. 6)", help: "Call checkConsent() or add @consent_required annotation before processing PII data." },
  [ErrorCode.ASYNC_START_NOT_WAITED]: { code: ErrorCode.ASYNC_START_NOT_WAITED, category: 'async', severity: 'error', message: "Started async task '{task}' not waited", help: "Call wait on started async tasks to ensure completion." },
  [ErrorCode.ASYNC_WAIT_NOT_STARTED]: { code: ErrorCode.ASYNC_WAIT_NOT_STARTED, category: 'async', severity: 'error', message: "Waiting for async task '{task}' that was never started", help: "Ensure the task name in wait matches a started task." },
  [ErrorCode.ASYNC_DUPLICATE_START]: { code: ErrorCode.ASYNC_DUPLICATE_START, category: 'async', severity: 'error', message: "Async task '{task}' started multiple times ({count} occurrences)", help: "Avoid starting the same task multiple times; reuse or rename." },
  [ErrorCode.ASYNC_DUPLICATE_WAIT]: { code: ErrorCode.ASYNC_DUPLICATE_WAIT, category: 'async', severity: 'warning', message: "Async task '{task}' waited multiple times ({count} occurrences)", help: "Ensure each task is waited on only once, or use a separate synchronization mechanism." },
  [ErrorCode.ASYNC_WAIT_BEFORE_START]: { code: ErrorCode.ASYNC_WAIT_BEFORE_START, category: 'async', severity: 'error', message: "Wait for async task '{task}' occurs before any matching start", help: "Execute start before wait, and ensure both are on compatible control paths." },
  [ErrorCode.PII_IMPLICIT_UPLEVEL]: { code: ErrorCode.PII_IMPLICIT_UPLEVEL, category: 'type', severity: 'warning', message: "Implicit PII level escalation detected: {source} -> {target}", help: "Add explicit type annotations for level changes to aid auditing." },
  [ErrorCode.PII_SINK_UNKNOWN]: { code: ErrorCode.PII_SINK_UNKNOWN, category: 'type', severity: 'warning', message: "PII data may flow to {sinkKind} without annotation", help: "Add @pii annotation to track sensitive data flow." },
  [ErrorCode.WORKFLOW_RETRY_INCONSISTENT]: { code: ErrorCode.WORKFLOW_RETRY_INCONSISTENT, category: 'type', severity: 'warning', message: "Workflow retry configuration may be unreasonable: {reason}", help: "Check the combination of total wait time, maxAttempts, and backoff strategy." },
  [ErrorCode.WORKFLOW_TIMEOUT_UNREASONABLE]: { code: ErrorCode.WORKFLOW_TIMEOUT_UNREASONABLE, category: 'type', severity: 'warning', message: "Workflow timeout configuration may be unreasonable: {reason}", help: "Check whether the timeout value is too large or too small." },
};

/**
 * 使用命名参数填充错误消息模板。
 * 可选传入 lexicon 以获取本地化翻译。
 */
export function formatErrorMessage(
  code: ErrorCode,
  params: Record<string, string | number>,
  diagnosticMessages?: Readonly<Partial<Record<string, string>>>,
): string {
  const template = diagnosticMessages?.[code] ?? ERROR_MESSAGES[code] ?? "";
  return template.replace(/\{(\w+)\}/g, (_, key) => {
    const value = params[key];
    return value === undefined ? `{${key}}` : String(value);
  });
}

/**
 * 获取详细元数据，包含分类与帮助信息。
 */
export function getErrorMetadata(code: ErrorCode): ErrorMetadata {
  return ERROR_METADATA[code];
}
