// @generated — 由 scripts/generate-lexicons.ts 自动生成，请勿手动修改

import { SemanticTokenKind } from '../token-kind.js';
import type { Lexicon } from './types.js';

export const DE_DE: Lexicon = {
  id: 'de-DE',
  name: 'Deutsch',
  direction: 'ltr',

  keywords: {
    [SemanticTokenKind.MODULE_DECL]: 'Modul',
    [SemanticTokenKind.IMPORT]: 'verwende',
    [SemanticTokenKind.IMPORT_ALIAS]: 'als',
    [SemanticTokenKind.TYPE_DEF]: 'Definiere',
    [SemanticTokenKind.TYPE_WITH]: 'mit',
    [SemanticTokenKind.TYPE_HAS]: 'hat',
    [SemanticTokenKind.TYPE_ONE_OF]: 'als eines von',
    [SemanticTokenKind.FUNC_TO]: 'Regel',
    [SemanticTokenKind.FUNC_GIVEN]: 'gegeben',
    [SemanticTokenKind.FUNC_PRODUCE]: 'liefert',
    [SemanticTokenKind.FUNC_PERFORMS]: 'fuehrt aus',
    [SemanticTokenKind.IF]: 'wenn',
    [SemanticTokenKind.OTHERWISE]: 'sonst',
    [SemanticTokenKind.MATCH]: 'pruefe',
    [SemanticTokenKind.WHEN]: 'bei',
    [SemanticTokenKind.RETURN]: 'gib zurueck',
    [SemanticTokenKind.RESULT_IS]: 'Ergebnis ist',
    [SemanticTokenKind.FOR_EACH]: 'fuer jedes',
    [SemanticTokenKind.IN]: 'in',
    [SemanticTokenKind.LET]: 'sei',
    [SemanticTokenKind.BE]: 'gleich',
    [SemanticTokenKind.SET]: 'setze',
    [SemanticTokenKind.TO_WORD]: 'auf',
    [SemanticTokenKind.OR]: 'oder',
    [SemanticTokenKind.AND]: 'und',
    [SemanticTokenKind.NOT]: 'nicht',
    [SemanticTokenKind.PLUS]: 'plus',
    [SemanticTokenKind.MINUS_WORD]: 'minus',
    [SemanticTokenKind.TIMES]: 'mal',
    [SemanticTokenKind.DIVIDED_BY]: 'geteilt durch',
    [SemanticTokenKind.LESS_THAN]: 'kleiner als',
    [SemanticTokenKind.GREATER_THAN]: 'groesser als',
    [SemanticTokenKind.EQUALS_TO]: 'entspricht',
    [SemanticTokenKind.IS]: 'ist',
    [SemanticTokenKind.UNDER]: 'unter',
    [SemanticTokenKind.OVER]: 'ueber',
    [SemanticTokenKind.MORE_THAN]: 'mehr als',
    [SemanticTokenKind.MAYBE]: 'vielleicht',
    [SemanticTokenKind.OPTION_OF]: 'Option aus',
    [SemanticTokenKind.RESULT_OF]: 'Ergebnis aus',
    [SemanticTokenKind.OK_OF]: 'ok von',
    [SemanticTokenKind.ERR_OF]: 'Fehler von',
    [SemanticTokenKind.SOME_OF]: 'einige von',
    [SemanticTokenKind.NONE]: 'keines',
    [SemanticTokenKind.TRUE]: 'wahr',
    [SemanticTokenKind.FALSE]: 'falsch',
    [SemanticTokenKind.NULL]: 'null',
    [SemanticTokenKind.TEXT]: 'Text',
    [SemanticTokenKind.INT_TYPE]: 'Ganzzahl',
    [SemanticTokenKind.FLOAT_TYPE]: 'Dezimal',
    [SemanticTokenKind.BOOL_TYPE]: 'Boolesch',
    [SemanticTokenKind.IO]: 'IO',
    [SemanticTokenKind.CPU]: 'CPU',
    [SemanticTokenKind.WORKFLOW]: 'Arbeitsablauf',
    [SemanticTokenKind.STEP]: 'Schritt',
    [SemanticTokenKind.DEPENDS]: 'haengt ab',
    [SemanticTokenKind.ON]: 'von',
    [SemanticTokenKind.COMPENSATE]: 'kompensiere',
    [SemanticTokenKind.RETRY]: 'wiederhole',
    [SemanticTokenKind.TIMEOUT]: 'Zeitlimit',
    [SemanticTokenKind.MAX_ATTEMPTS]: 'maximale Versuche',
    [SemanticTokenKind.BACKOFF]: 'Wartezeit',
    [SemanticTokenKind.WITHIN]: 'innerhalb',
    [SemanticTokenKind.SCOPE]: 'Bereich',
    [SemanticTokenKind.START]: 'starte',
    [SemanticTokenKind.ASYNC]: 'asynchron',
    [SemanticTokenKind.AWAIT]: 'warte',
    [SemanticTokenKind.WAIT_FOR]: 'warte auf',
    [SemanticTokenKind.REQUIRED]: 'erforderlich',
    [SemanticTokenKind.BETWEEN]: 'zwischen',
    [SemanticTokenKind.AT_LEAST]: 'mindestens',
    [SemanticTokenKind.AT_MOST]: 'hoechstens',
    [SemanticTokenKind.MATCHING]: 'passend',
    [SemanticTokenKind.PATTERN]: 'Muster',
  },

  punctuation: {
    statementEnd: '.',
    listSeparator: ',',
    enumSeparator: ',',
    blockStart: ':',
    stringQuotes: {
      open: '"',
      close: '"',
    },
  },

  canonicalization: {
    fullWidthToHalf: false,
    whitespaceMode: 'english',
    removeArticles: true,
    articles: ['der', 'die', 'das', 'ein', 'eine', 'einen', 'einem', 'einer', 'eines'],
    customRules: [
      { name: 'oe-to-ö', pattern: 'oe', replacement: 'ö' },
      { name: 'ue-to-ü', pattern: 'ue', replacement: 'ü' },
      { name: 'ae-to-ä', pattern: 'ae', replacement: 'ä' },
      { name: 'ss-to-ß-grösser', pattern: '\\bgrösser\\b', replacement: 'größer' },
      { name: 'ss-to-ß-gross', pattern: '\\bgross\\b', replacement: 'groß' },
    ],
    allowedDuplicates: [
      [SemanticTokenKind.UNDER, SemanticTokenKind.LESS_THAN],
      [SemanticTokenKind.OVER, SemanticTokenKind.GREATER_THAN, SemanticTokenKind.MORE_THAN],
    ],
  },

  messages: {
    unexpectedToken: 'Unerwartetes Symbol: {token}',
    expectedKeyword: 'Erwartetes Schluesselwort: {keyword}',
    undefinedVariable: 'Nicht definierte Variable: {name}',
    typeMismatch: 'Typkonflikt: erwartet {expected}, erhalten {actual}',
    unterminatedString: 'Nicht abgeschlossenes Zeichenkettenliteral',
    invalidIndentation: 'Ungueltige Einrueckung: muss ein Vielfaches von 2 Leerzeichen sein',
  },
};
