// @generated — 由 scripts/generate-lexicons.ts 自动生成，请勿手动修改

import { SemanticTokenKind } from '../token-kind.js';
import type { Lexicon } from './types.js';

export const ZH_CN: Lexicon = {
  id: 'zh-CN',
  name: '简体中文',
  direction: 'ltr',

  keywords: {
    [SemanticTokenKind.MODULE_DECL]: '模块',
    [SemanticTokenKind.IMPORT]: '引用',
    [SemanticTokenKind.IMPORT_ALIAS]: '作为',
    [SemanticTokenKind.TYPE_DEF]: '定义',
    [SemanticTokenKind.TYPE_WITH]: '包含',
    [SemanticTokenKind.TYPE_HAS]: '包含',
    [SemanticTokenKind.TYPE_ONE_OF]: '为以下之一',
    [SemanticTokenKind.FUNC_TO]: '规则',
    [SemanticTokenKind.FUNC_GIVEN]: '给定',
    [SemanticTokenKind.FUNC_PRODUCE]: '产出',
    [SemanticTokenKind.FUNC_PERFORMS]: '执行',
    [SemanticTokenKind.IF]: '如果',
    [SemanticTokenKind.OTHERWISE]: '否则',
    [SemanticTokenKind.MATCH]: '若',
    [SemanticTokenKind.WHEN]: '为',
    [SemanticTokenKind.RETURN]: '返回',
    [SemanticTokenKind.RESULT_IS]: '结果为',
    [SemanticTokenKind.FOR_EACH]: '对每个',
    [SemanticTokenKind.IN]: '在',
    [SemanticTokenKind.LET]: '令',
    [SemanticTokenKind.BE]: '为',
    [SemanticTokenKind.SET]: '将',
    [SemanticTokenKind.TO_WORD]: '设为',
    [SemanticTokenKind.OR]: '或',
    [SemanticTokenKind.AND]: '且',
    [SemanticTokenKind.NOT]: '非',
    [SemanticTokenKind.PLUS]: '加',
    [SemanticTokenKind.MINUS_WORD]: '减',
    [SemanticTokenKind.TIMES]: '乘',
    [SemanticTokenKind.DIVIDED_BY]: '除以',
    [SemanticTokenKind.LESS_THAN]: '小于',
    [SemanticTokenKind.GREATER_THAN]: '大于',
    [SemanticTokenKind.EQUALS_TO]: '等于',
    [SemanticTokenKind.IS]: '是',
    [SemanticTokenKind.UNDER]: '不足',
    [SemanticTokenKind.OVER]: '超过',
    [SemanticTokenKind.MORE_THAN]: '多于',
    [SemanticTokenKind.MAYBE]: '可选',
    [SemanticTokenKind.OPTION_OF]: '选项',
    [SemanticTokenKind.RESULT_OF]: '结果',
    [SemanticTokenKind.OK_OF]: '成功',
    [SemanticTokenKind.ERR_OF]: '失败',
    [SemanticTokenKind.SOME_OF]: '有值',
    [SemanticTokenKind.NONE]: '无',
    [SemanticTokenKind.TRUE]: '真',
    [SemanticTokenKind.FALSE]: '假',
    [SemanticTokenKind.NULL]: '空',
    [SemanticTokenKind.TEXT]: '文本',
    [SemanticTokenKind.INT_TYPE]: '整数',
    [SemanticTokenKind.FLOAT_TYPE]: '小数',
    [SemanticTokenKind.BOOL_TYPE]: '布尔',
    [SemanticTokenKind.IO]: '输入输出',
    [SemanticTokenKind.CPU]: '计算',
    [SemanticTokenKind.WORKFLOW]: '流程',
    [SemanticTokenKind.STEP]: '步骤',
    [SemanticTokenKind.DEPENDS]: '依赖',
    [SemanticTokenKind.ON]: '于',
    [SemanticTokenKind.COMPENSATE]: '补偿',
    [SemanticTokenKind.RETRY]: '重试',
    [SemanticTokenKind.TIMEOUT]: '超时',
    [SemanticTokenKind.MAX_ATTEMPTS]: '最多尝试',
    [SemanticTokenKind.BACKOFF]: '退避',
    [SemanticTokenKind.WITHIN]: '范围',
    [SemanticTokenKind.SCOPE]: '域',
    [SemanticTokenKind.START]: '启动',
    [SemanticTokenKind.ASYNC]: '异步',
    [SemanticTokenKind.AWAIT]: '等待',
    [SemanticTokenKind.WAIT_FOR]: '等候',
    [SemanticTokenKind.REQUIRED]: '必填',
    [SemanticTokenKind.BETWEEN]: '介于',
    [SemanticTokenKind.AT_LEAST]: '至少',
    [SemanticTokenKind.AT_MOST]: '至多',
    [SemanticTokenKind.MATCHING]: '匹配',
    [SemanticTokenKind.PATTERN]: '模式',
  },

  punctuation: {
    statementEnd: '。',
    listSeparator: '，',
    enumSeparator: '、',
    blockStart: '：',
    stringQuotes: {
      open: '「',
      close: '」',
    },
  },

  canonicalization: {
    fullWidthToHalf: true,
    whitespaceMode: 'chinese',
    removeArticles: false,
    allowedDuplicates: [
      [SemanticTokenKind.BE, SemanticTokenKind.WHEN],
      [SemanticTokenKind.TYPE_HAS, SemanticTokenKind.TYPE_WITH],
      [SemanticTokenKind.LESS_THAN, SemanticTokenKind.UNDER],
      [SemanticTokenKind.OVER, SemanticTokenKind.GREATER_THAN, SemanticTokenKind.MORE_THAN],
    ],
    compoundPatterns: [
      {
        name: 'match-when',
        opener: SemanticTokenKind.MATCH,
        contextualKeywords: [
          SemanticTokenKind.WHEN,
        ],
        closer: 'DEDENT',
      },
      {
        name: 'let-be',
        opener: SemanticTokenKind.LET,
        contextualKeywords: [
          SemanticTokenKind.BE,
        ],
        closer: 'NEWLINE',
      },
    ],
  },

  messages: {
    unexpectedToken: '意外的符号：{token}',
    expectedKeyword: '期望关键词：{keyword}',
    undefinedVariable: '未定义的变量：{name}',
    typeMismatch: '类型不匹配：期望 {expected}，实际 {actual}',
    unterminatedString: '未终止的字符串字面量',
    invalidIndentation: '无效的缩进：必须是 2 个空格的倍数',
  },
};
