/**
 * Provenance 元數據接口
 *
 * 記錄 AI 生成代碼的來源信息
 */
export interface ProvenanceMetadata {
  /**
   * 使用的 LLM 模型名稱
   * 例如：gpt-4, claude-3-5-sonnet-20241022
   */
  model: string;

  /**
   * LLM provider 名稱
   * 例如：openai, anthropic
   */
  provider: string;

  /**
   * 用戶輸入的英文描述（prompt）
   */
  prompt: string;

  /**
   * 生成時間戳（ISO 8601 格式）
   */
  timestamp: string;

  /**
   * 是否通過驗證
   */
  validated: boolean;
}

/**
 * Provenance Tracker
 *
 * 負責生成和管理 AI 生成代碼的來源元數據註釋頭
 */
export class ProvenanceTracker {
  /**
   * 生成 provenance 註釋頭
   *
   * @param metadata - Provenance 元數據
   * @returns 格式化的註釋頭字符串
   */
  generateHeader(metadata: ProvenanceMetadata): string {
    const lines = [
      '// ========================================',
      '// Generated by: Aster AI Code Generator',
      `// Model: ${metadata.model}`,
      `// Provider: ${metadata.provider}`,
      `// Prompt: ${this.escapePrompt(metadata.prompt)}`,
      `// Timestamp: ${metadata.timestamp}`,
      `// Validated: ${metadata.validated ? 'true' : 'false'}`,
      '// ========================================',
      '',  // 空行分隔註釋和代碼
    ];
    return lines.join('\n');
  }

  /**
   * 添加 provenance 註釋頭到 CNL 代碼
   *
   * @param code - 原始 CNL 代碼
   * @param metadata - Provenance 元數據
   * @returns 帶註釋頭的 CNL 代碼
   */
  addProvenanceToCode(code: string, metadata: ProvenanceMetadata): string {
    const header = this.generateHeader(metadata);
    return `${header}${code}`;
  }

  /**
   * 轉義 prompt 中的特殊字符
   *
   * 避免換行符和過長的 prompt 破壞註釋格式
   *
   * @param prompt - 原始 prompt
   * @returns 轉義後的 prompt
   */
  private escapePrompt(prompt: string): string {
    // 替換換行符為空格，去除多餘空格
    const cleaned = prompt.replace(/[\r\n]+/g, ' ').replace(/\s+/g, ' ').trim();

    // 截斷過長的 prompt
    const maxLength = 200;
    if (cleaned.length > maxLength) {
      return `${cleaned.slice(0, maxLength)}...`;
    }

    return cleaned;
  }

  /**
   * 從代碼中提取 provenance 元數據
   *
   * 可選功能，用於分析已生成的代碼
   *
   * @param code - 帶 provenance 註釋的 CNL 代碼
   * @returns Provenance 元數據，如果無法提取則返回 null
   */
  extractProvenance(code: string): ProvenanceMetadata | null {
    try {
      // 匹配 provenance 註釋頭中的各個字段
      const modelMatch = code.match(/\/\/ Model: (.+)/);
      const providerMatch = code.match(/\/\/ Provider: (.+)/);
      const promptMatch = code.match(/\/\/ Prompt: (.+)/);
      const timestampMatch = code.match(/\/\/ Timestamp: (.+)/);
      const validatedMatch = code.match(/\/\/ Validated: (true|false)/);

      // 所有字段都匹配才返回結果
      if (
        modelMatch && modelMatch[1] &&
        providerMatch && providerMatch[1] &&
        promptMatch && promptMatch[1] &&
        timestampMatch && timestampMatch[1] &&
        validatedMatch && validatedMatch[1]
      ) {
        return {
          model: modelMatch[1].trim(),
          provider: providerMatch[1].trim(),
          prompt: promptMatch[1].trim(),
          timestamp: timestampMatch[1].trim(),
          validated: validatedMatch[1] === 'true',
        };
      }

      return null;
    } catch (error) {
      // 解析失敗返回 null
      console.error(error);
      return null;
    }
  }
}
