// @generated — 由 scripts/generate-vocabularies.ts 自动生成，请勿手动修改

import { type DomainVocabulary, IdentifierKind } from '../types.js';

export const FINANCE_LOAN_DE_DE: DomainVocabulary = {
  id: 'finance.loan',
  name: 'Kreditwesen',
  locale: 'de-DE',
  version: '1.0.0',

  metadata: {
    author: 'Aster Team',
    createdAt: '2025-01-06',
    description: 'Kreditwesen Fachbegriffe auf Deutsch',
  },

  structs: [
    {
      canonical: 'Applicant',
      localized: 'Antragsteller',
      kind: IdentifierKind.STRUCT,
      aliases: ['Kreditnehmer', 'Darlehensnehmer'],
    },
    {
      canonical: 'LoanRequest',
      localized: 'Kreditantrag',
      kind: IdentifierKind.STRUCT,
      aliases: ['Darlehensantrag'],
    },
    {
      canonical: 'ApprovalResult',
      localized: 'Genehmigungsergebnis',
      kind: IdentifierKind.STRUCT,
      aliases: ['Pruefungsergebnis'],
    },
    {
      canonical: 'CreditReport',
      localized: 'Bonitaetsbericht',
      kind: IdentifierKind.STRUCT,
      aliases: ['Schufa-Auskunft'],
    },
    {
      canonical: 'Collateral',
      localized: 'Sicherheit',
      kind: IdentifierKind.STRUCT,
      aliases: ['Buergschaft'],
    },
    {
      canonical: 'RepaymentPlan',
      localized: 'Tilgungsplan',
      kind: IdentifierKind.STRUCT,
      aliases: ['Rueckzahlungsplan'],
    },
  ],

  fields: [
    {
      canonical: 'id',
      localized: 'Kennung',
      kind: IdentifierKind.FIELD,
      parent: 'Applicant',
      aliases: ['Nummer'],
    },
    {
      canonical: 'age',
      localized: 'Alter',
      kind: IdentifierKind.FIELD,
      parent: 'Applicant',
    },
    {
      canonical: 'income',
      localized: 'Einkommen',
      kind: IdentifierKind.FIELD,
      parent: 'Applicant',
      aliases: ['Gehalt'],
    },
    {
      canonical: 'creditScore',
      localized: 'Bonitaetsnote',
      kind: IdentifierKind.FIELD,
      parent: 'Applicant',
      aliases: ['Kreditwuerdigkeit'],
    },
    {
      canonical: 'workYears',
      localized: 'Berufsjahre',
      kind: IdentifierKind.FIELD,
      parent: 'Applicant',
      aliases: ['Berufserfahrung'],
    },
    {
      canonical: 'debtRatio',
      localized: 'Verschuldungsgrad',
      kind: IdentifierKind.FIELD,
      parent: 'Applicant',
      aliases: ['Schuldenquote'],
    },
    {
      canonical: 'employer',
      localized: 'Arbeitgeber',
      kind: IdentifierKind.FIELD,
      parent: 'Applicant',
    },
    {
      canonical: 'name',
      localized: 'Name',
      kind: IdentifierKind.FIELD,
      parent: 'Applicant',
    },
    {
      canonical: 'idNumber',
      localized: 'Ausweisnummer',
      kind: IdentifierKind.FIELD,
      parent: 'Applicant',
      aliases: ['Personalausweisnummer'],
    },
    {
      canonical: 'amount',
      localized: 'Betrag',
      kind: IdentifierKind.FIELD,
      parent: 'LoanRequest',
      aliases: ['Kreditbetrag', 'Darlehenssumme'],
    },
    {
      canonical: 'termMonths',
      localized: 'Laufzeit',
      kind: IdentifierKind.FIELD,
      parent: 'LoanRequest',
      aliases: ['Kreditlaufzeit'],
    },
    {
      canonical: 'purpose',
      localized: 'Verwendungszweck',
      kind: IdentifierKind.FIELD,
      parent: 'LoanRequest',
      aliases: ['Kreditzweck'],
    },
    {
      canonical: 'loanType',
      localized: 'Kreditart',
      kind: IdentifierKind.FIELD,
      parent: 'LoanRequest',
      aliases: ['Darlehensart'],
    },
    {
      canonical: 'approved',
      localized: 'genehmigt',
      kind: IdentifierKind.FIELD,
      parent: 'ApprovalResult',
    },
    {
      canonical: 'reason',
      localized: 'Grund',
      kind: IdentifierKind.FIELD,
      parent: 'ApprovalResult',
      aliases: ['Begruendung'],
    },
    {
      canonical: 'interestRate',
      localized: 'Zinssatz',
      kind: IdentifierKind.FIELD,
      parent: 'ApprovalResult',
      aliases: ['Effektivzins'],
    },
    {
      canonical: 'monthlyPayment',
      localized: 'Monatsrate',
      kind: IdentifierKind.FIELD,
      parent: 'ApprovalResult',
      aliases: ['Monatliche Rate'],
    },
    {
      canonical: 'approvedAmount',
      localized: 'GenehmigterBetrag',
      kind: IdentifierKind.FIELD,
      parent: 'ApprovalResult',
      aliases: ['Genehmigter Betrag', 'Kreditrahmen'],
    },
    {
      canonical: 'score',
      localized: 'Punktzahl',
      kind: IdentifierKind.FIELD,
      parent: 'CreditReport',
      aliases: ['Bewertung'],
    },
    {
      canonical: 'level',
      localized: 'Stufe',
      kind: IdentifierKind.FIELD,
      parent: 'CreditReport',
      aliases: ['Bonitaetsstufe'],
    },
    {
      canonical: 'latePayments',
      localized: 'Zahlungsverzoegerungen',
      kind: IdentifierKind.FIELD,
      parent: 'CreditReport',
      aliases: ['Zahlungsrueckstaende'],
    },
    {
      canonical: 'totalDebt',
      localized: 'Gesamtverschuldung',
      kind: IdentifierKind.FIELD,
      parent: 'CreditReport',
      aliases: ['Gesamtschulden'],
    },
    {
      canonical: 'type',
      localized: 'Typ',
      kind: IdentifierKind.FIELD,
      parent: 'Collateral',
      aliases: ['Art'],
    },
    {
      canonical: 'value',
      localized: 'Wert',
      kind: IdentifierKind.FIELD,
      parent: 'Collateral',
      aliases: ['Schaetzwert'],
    },
    {
      canonical: 'description',
      localized: 'Beschreibung',
      kind: IdentifierKind.FIELD,
      parent: 'Collateral',
    },
  ],

  functions: [
    {
      canonical: 'evaluateLoan',
      localized: 'KreditBewerten',
      kind: IdentifierKind.FUNCTION,
      aliases: ['Kredit bewerten', 'Kreditpruefung'],
    },
    {
      canonical: 'checkBasicQualification',
      localized: 'GrundvoraussetzungenPruefen',
      kind: IdentifierKind.FUNCTION,
      aliases: ['Grundvoraussetzungen pruefen'],
    },
    {
      canonical: 'calculateCreditLevel',
      localized: 'BonitaetsstufeBerechnen',
      kind: IdentifierKind.FUNCTION,
      aliases: ['Bonitaetsstufe berechnen'],
    },
    {
      canonical: 'calculateInterestRate',
      localized: 'ZinssatzBerechnen',
      kind: IdentifierKind.FUNCTION,
      aliases: ['Zinssatz berechnen'],
    },
    {
      canonical: 'calculateMonthlyPayment',
      localized: 'MonatsrateBerechnen',
      kind: IdentifierKind.FUNCTION,
      aliases: ['Monatsrate berechnen'],
    },
    {
      canonical: 'checkDebtRatio',
      localized: 'VerschuldungsgradPruefen',
      kind: IdentifierKind.FUNCTION,
      aliases: ['Verschuldungsgrad pruefen'],
    },
    {
      canonical: 'assessCollateral',
      localized: 'SicherheitBewerten',
      kind: IdentifierKind.FUNCTION,
      aliases: ['Sicherheit bewerten'],
    },
  ],

  enumValues: [
    {
      canonical: 'Excellent',
      localized: 'Ausgezeichnet',
      kind: IdentifierKind.ENUM_VALUE,
    },
    {
      canonical: 'Good',
      localized: 'Gut',
      kind: IdentifierKind.ENUM_VALUE,
    },
    {
      canonical: 'Fair',
      localized: 'Befriedigend',
      kind: IdentifierKind.ENUM_VALUE,
      aliases: ['Ausreichend'],
    },
    {
      canonical: 'Poor',
      localized: 'Mangelhaft',
      kind: IdentifierKind.ENUM_VALUE,
      aliases: ['Ungenuegend'],
    },
    {
      canonical: 'Personal',
      localized: 'Privatkredit',
      kind: IdentifierKind.ENUM_VALUE,
      aliases: ['Konsumentenkredit'],
    },
    {
      canonical: 'Mortgage',
      localized: 'Hypothek',
      kind: IdentifierKind.ENUM_VALUE,
      aliases: ['Baufinanzierung', 'Immobilienkredit'],
    },
    {
      canonical: 'Business',
      localized: 'Geschaeftskredit',
      kind: IdentifierKind.ENUM_VALUE,
      aliases: ['Firmenkredit', 'Unternehmenskredit'],
    },
    {
      canonical: 'Auto',
      localized: 'Autokredit',
      kind: IdentifierKind.ENUM_VALUE,
      aliases: ['Fahrzeugfinanzierung'],
    },
  ],
};
